root -q -b "skim_for_MLevaluation_zllcontrol.cpp(\"root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/mratti/merged_nanoMT2/2016_V08_V00_v2/merged/superMerged_noDupl.root\",\"/scratch/wjin/featurereduced4/rootfiles_zinvcontrol/2016/data/superMerged_noDupl.root\",\"Events\",0)"
root -q -b "skim_for_MLevaluation_zllcontrol.cpp(\"root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/mratti/merged_nanoMT2/2017_V08_V00_v1/merged/superMerged_noDupl.root\",\"/scratch/wjin/featurereduced4/rootfiles_zinvcontrol/2017/data/superMerged_noDupl.root\",\"Events\",0)"
root -q -b "skim_for_MLevaluation_zllcontrol.cpp(\"root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/mratti/merged_nanoMT2/2018_V08_V01_v0/merged/superMerged_noDupl.root\",\"/scratch/wjin/featurereduced4/rootfiles_zinvcontrol/2018/data/superMerged_noDupl.root\",\"Events\",0)"

root -q -b "skim_for_MLevaluation_llepcontrol.cpp(\"root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/mratti/merged_nanoMT2/2016_V08_V00_v2/merged/superMerged_noDupl.root\",\"/scratch/wjin/featurereduced4/rootfiles_llcontrol/2016/data/superMerged_noDupl.root\",\"Events\",0)"
root -q -b "skim_for_MLevaluation_llepcontrol.cpp(\"root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/mratti/merged_nanoMT2/2017_V08_V00_v1/merged/superMerged_noDupl.root\",\"/scratch/wjin/featurereduced4/rootfiles_llcontrol/2017/data/superMerged_noDupl.root\",\"Events\",0)"
root -q -b "skim_for_MLevaluation_llepcontrol.cpp(\"root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/mratti/merged_nanoMT2/2018_V08_V01_v0/merged/superMerged_noDupl.root\",\"/scratch/wjin/featurereduced4/rootfiles_llcontrol/2018/data/superMerged_noDupl.root\",\"Events\",0)"

root -q -b "skim_for_MLevaluation_signalregion.cpp(\"root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/mratti/merged_nanoMT2/2016_V08_V00_v2/merged/superMerged_noDupl.root\",\"/scratch/wjin/featurereduced4/rootfiles/2016/data/superMerged_noDupl.root\",\"Events\",0)"
root -q -b "skim_for_MLevaluation_signalregion.cpp(\"root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/mratti/merged_nanoMT2/2017_V08_V00_v1/merged/superMerged_noDupl.root\",\"/scratch/wjin/featurereduced4/rootfiles/2017/data/superMerged_noDupl.root\",\"Events\",0)"
root -q -b "skim_for_MLevaluation_signalregion.cpp(\"root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/mratti/merged_nanoMT2/2018_V08_V01_v0/merged/superMerged_noDupl.root\",\"/scratch/wjin/featurereduced4/rootfiles/2018/data/superMerged_noDupl.root\",\"Events\",0)"
