./regionEventYields config_MLoptimize_2016_ForT1bbbb_btagexclu_noMLcutallevents_o signal T1bbbb
./regionEventYields config_MLoptimize_2017_ForT1bbbb_btagexclu_noMLcutallevents_o signal T1bbbb
./regionEventYields config_MLoptimize_2018_ForT1bbbb_btagexclu_noMLcutallevents_o signal T1bbbb
#hadd EventYields_config_MLoptimize_2016_ForT1bbbb_btagexclu_noMLcutallevents_o/analyses_signals_merged.root EventYields_config_MLoptimize_2016_ForT1bbbb_btagexclu_noMLcutallevents_o/analyses.root EventYields_config_MLoptimize_2017_ForT1bbbb_btagexclu_noMLcutallevents_o/analyses.root EventYields_config_MLoptimize_2018_ForT1bbbb_btagexclu_noMLcutallevents_o/analyses.root
