./regionEventYields config_MLoptimize_2016_ForT1bbbb_btagexclu signal T1bbbb
./regionEventYields config_MLoptimize_2017_ForT1bbbb_btagexclu signal T1bbbb
./regionEventYields config_MLoptimize_2018_ForT1bbbb_btagexclu signal T1bbbb
hadd EventYields_config_MLoptimize_2016_ForT1bbbb_btagexclu/analyses_signals_merged.root EventYields_config_MLoptimize_2016_ForT1bbbb_btagexclu/analyses.root EventYields_config_MLoptimize_2017_ForT1bbbb_btagexclu/analyses.root EventYields_config_MLoptimize_2018_ForT1bbbb_btagexclu/analyses.root
